# Generated by Django 5.1.3 on 2024-12-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_comment_phone_alter_quote_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date_posted', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('subtitle1', models.CharField(max_length=100)),
                ('subtitle2', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('footer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
