# Generated by Django 5.1.3 on 2024-12-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_blogpost_alter_comment_phone_alter_quote_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
